#import "settings.typ": addToPDFBookmark, fontsizes

#align(center)[
  #addToPDFBookmark("Abstract")
  #text(size: fontsizes.heading2)[*ABSTRACT*]
]
K-band Doppler radar can be used to detect atmospheric turbulence and estimate wind velocity and direction, but the weak turbulence echoes are often severely affected by noise, clutter, and multiple spectral peaks, particularly under low signal-to-noise ratio (SNR) conditions. To address these limitations, the paper proposes a Mutual Convolution Cost Function (MCCF) method for robust wind-profile estimation. The processing framework first preprocesses the coherent accumulation (CA) echo data to improve SNR and remove DC components and ground clutter. A space-time Doppler window is then adaptively established using the continuity of wind velocity in both altitude and time, together with wind-shear constraints, to limit the candidate spectral region. Within this window, mutual convolution between appropriately delayed signal segments is used to exploit the temporal stability of atmospheric echoes and the low correlation of noise and clutter. The resulting signal is further processed using an improved Mutual Convolution and Complex Least Mean Square (MCLMS) adaptive filter to suppress interference and enhance stable spectral components. Finally, a cost function combining spectral power and velocity continuity is applied to select the optimal Doppler spectral peak for each range bin and estimate the wind profile.

The proposed MCCF method is evaluated using low-SNR K-band wind-profiler data collected with the VORTRAD radar and is compared with Adaptive Moment Estimation (AME), Multiparameter Cost Function (MPCF), and Improved Moment Estimation (IME) methods. Experimental results show that the MCLMS filtering stage reduces the occurrence of multiple spectral peaks and improves the echo SNR by approximately 2–4 dB. The MCCF method also produces more stable and physically continuous wind-velocity profiles under low-SNR and multiple-peak conditions, avoiding the selection of high-power clutter as the atmospheric signal. Validation against collocated LIDAR measurements demonstrates improved agreement between the radar-derived and LIDAR wind velocities, with the MCCF method achieving correlation coefficients of up to approximately 0.95, compared with values below 0.9 for the other evaluated methods. These results demonstrate that the proposed MCCF framework can improve the robustness and accuracy of wind-profile estimation in challenging radar measurement conditions characterized by weak atmospheric echoes, strong noise, clutter, and multiple Doppler spectral peaks.


#pagebreak()