#import "settings.typ": flex-caption, report-title
= Introduction <sec:intro>

The research paper titled _"#report-title"_ proposes a new method to estimate wind profiles by combining several methods including MCCF. The paper primarily focuses K-Band radar and on its potential application of such as efficient wind energy generation as well as challenges posed by seasonal atmospheric variation in measurement of near surface ($<1$ km) wind turbulence.

== Problem Addressed
The primary problem is that radar echoes from atmospheric turbulence are often heavily corrupted by strong background noise, resulting in a low SNR. This issue worsens in colder environments where decreased air density further weakens the returning signal. Additionally, the circular detection area of the radar antenna (widening of beam in higher altitudes) causes the returning echoes to frequently contain multiple spectral peaks. This makes it difficult to isolate the true frequency offset associated with the actual wind target.

Traditional data processing methods attempt to extract the wind profile by analyzing coherent accumulation (CA) signals with a cost function. While these methods work well when the SNR is high, their accuracy deteriorates under low SNR conditions with multiple competing peaks. Under these constraints, traditional algorithms become highly susceptible to clutter and noise, often mistaking false peaks for the true wind signal, which degrades the overall accuracy of the radar.

== Overview of Process
The paper describes a 5 step process to extract wind velocity:
+ *Signal Preprocessing*: Performs CA which boosts the steady wind signal and averages out random background noise. Resamples data into specific altitude slices (range bins) to track temporal changes in wind speeds at different heights. Finally atmospheric clutter and ground reflections are removed.
+ *Space-Time Doppler Window*: The system uses recent measurements to set a window in both spacial and temporal range. Any frequency peaks that fall far outside this window are ignored.
+ *Mutual Convolution*: The system takes an initial segment of radar signal at a height and compares it against slightly delayed segments of the same signal. It applies convolution with them and because random noise does not repeat exactly over time, it is canceled out. The stable wind signal persists across the segments and is amplified.
+ *Modified Complex Least Mean Square (MCLMS) Filter*: It minimizes the difference between the desired signal and the actual output, further smoothing the data and eliminating leftover clutter.
+ *Cost Function Evaluation*: The final step chooses the correct wind speed from any remaining signal peaks, by assigning penalty score to different aspects of the peaks and selecting the one with least penalty.

Finally the results are validates using data from a LIDAR operating in the same time period. The overall process is summarized in @img:oper
#figure(
  caption: [Overall flow of the method],
  image("images/diagram.jpg", height: 10cm),
)<img:oper>

== Experiment Setup
The authors have utilized the K-band vortex radar (VORTRAD) as experiment equipment provided by Suzhou Dufeng Technology Company, which estimates wind profile by detecting Doppler frequency offset generated by atmospheric turbulence. The specification of VORTRAD system is given in @tab:spec.

The experiment setup is shown in @img:setup. The VORTRAD is equipped with a shield and two devices are placed 3 m apart. The distance resolution, velocity resolution, and measurement distance of the two devices are consistent, and the accuracy of this LIDAR under clear sky conditions reaches 99%.
For comparing the effectiveness of proposed method, researchers have compared MCCF against CA, AME, MPCF, and IME using SNR and Correlation coefficient

#set text(size: 10pt)
#figure(
	caption: [Specification of VORTRAD Radar],
  table(
    columns: (3cm, 5cm, 5cm),
    stroke: none,
		row-gutter: -3pt,
    [*Number*], table.vline(), [*Specification*], table.vline(), [*Value*],
    table.hline(),
    [1], [Frequency band], [K-band],
    [2], [Operation mode], [Single frequency pulse],
    [3], [Number of beams], [4 (East, South, West, North)],
    [4], [Tilt Angle], [15°],
    [5], [Pulse period], [2us],
    [6], [Pulse width], [$approx$ 133.3ns],
    [7], [No.of coherent accumulation], [50],
    [8], [Slow sampling points], [2048],
    [9], [FFT points], [1024],
    [10], [Maximum range], [300m],
    [11], [Window coefficient], [2],
    [12], [Maximum radical velocity], [30 m/s],
    [13], [Radial velocity resolution], [0.06 m/s],
    [14], [Range resolution], [20m],
  ),
)<tab:spec>
#figure(
  caption: [Experiment setup],
  image("images/setup.jpg", height: 7cm),
)<img:setup>