#import "settings.typ": flex-caption
= Research Methodology
This section introduces the data processing algorithm in detail and mainly addresses the issues of low SNR and multiple spectral peaks by the MCCF algorithm.
The algorithm is divided into five parts, signal preprocessing, setting the space-time Doppler window, mutual convolution, MCLMS filter, and generating the cost function.

== Signal Preprocessing

This phase prepares data for MCCF algorithm. In this phase, 3 operations are performed on data:

=== Coherent Accumulation (CA)
Here atmospheric turbulence is characterized as a weak target. The model assumes that turbulence moves at a uniform velocity over a short period. Hence its echo is akin to a stable periodic signal. Conversely, noise exhibits instability and lacks periodicity. The CA adds and averages short segments of radar signals thereby reducing noise strength and amplifying turbulence echo. Throughout the paper 2-D matrix generated by the
result after N-order CA is represented as:

$ X = lr([x_(c 1)^T, x_(c 2)^T, dots, x_(c (N-1))^T, x_(c N)^T]) $

Where $x_(c i)$ is result of $i^"th"$ CA. (Hence the column vector of the X represents the result of one accumulation)

=== Slow Sampling
To detect the motion state of turbulence at different altitudes, we need to extract data from a specific range bin. When a pulse is transmitted, the radar receives echoes from all range bins (heights). After one Pulse Repetition Interval (PRI), it transmits the next pulse and repeats the process. For a single range gate (height), the radar stores one complex echo sample from every transmitted pulse. This sequence is called _slow-time signal_. To obtain this, a row vector from $X$ is used. This process is called _slow sampling_ in the distance dimension. The slow sampling frequency must satisfy the Nyquist criterion in order to avoid blurring the maximum turbulence velocity, and the slow sampling frequency $f_(d"min")$ can be given as

$ f_(d"min") = (4 v_max )/lambda $

where $v_max$ represents the maximum velocity range and $λ$ represents the work wavelength of the radar


=== DC and Clutter Removal
Hardware components and ground reflections create direct current (DC) interference, which shows up as clutter near the zero-frequency point. In case of VORTRAD which adopts a zero-intermediate-frequency RF transceiver architecture, produces  signal containing a large DC power, and ground clutter with a small frequency offset. The paper doesn't mention a particular clutter removal method.


== Setting the Space-Time Doppler Window
In this stage, the search window for peaks is reduced by using 2 property of wind velocity:
- Turbulent motion state between adjacent altitudes continuously changes and there is a maximum wind shear associated with a difference in altitude (typically less than 0.5 m/s in the range of 10 m and is less than 1 m/s in the range of 20 m).
- Wind velocity exhibits continuity over multiple pulse same altitude as shown in @img:cont

Therefore, when setting this search window (doppler window), it is essential to consider both spatial and temporal aspects. The size of doppler window.

#figure(
  caption: [Wind velocity over 50 consecutive groups at 100 m. (provided by researchers)],
  image(
    "images/temp-conti.jpg",
    height: 7cm,
  ),
)<img:cont>

The researchers have quantitatively modeled the window size using frequency offset corresponding to wind shear ($d_f$) and "window coefficient related to altitude interval" ($alpha$). First, considering space continuity, assuming that the spectrum estimation result of the previous range bin is $F_0$ , the
space Doppler window can be represented as
$ W_1 = (F_0 - alpha d_f, F_0 + alpha d_f) $

Where $d_f$ is given by:

$ d_f = V_d / d_v = V_d /(f_(d"min") lambda \/ L) $

Where $V_d$ = maximum value of wind shear and $L$ = number of points in FFT.


Now, considering time continuity, and assuming the previous spectrum estimation result at the same range bin is $T_0$, the time Doppler window can be represented as
$ W_2 = (T_0 - alpha d_f, T_0 + alpha d_f) $

The window used for peak estimation is intersection of these 2 windows, the researchers have termed this window as _space-time Doppler window_, expressed as:

$
  "ST"-"W" = cases(
    W_1 inter.big W_2 quad quad & "if" W_1 inter.big W_2 >= alpha d_f,
    W_1 & "else"
  )
$

An example case of ST--W and peak estimation is illustrated in @img:markings
#let img-h = 8.5cm
#figure(
  caption: flex-caption(
    [(a) spectra peak selection highlighted in red circles (b) Space (red) and Time (black) doppler windows marked],
    [Space-time doppler windows and peaks marked in a spectrum],
  ),
  grid(
    columns: 2,
    column-gutter: 10pt,
    [#image(
      "images/peaks.jpg",
      height: img-h,
    )],
    [#image(
      "images/windows.jpg",
      height: img-h,
    )],
  ),
)<img:markings>
== Mutual Convolution
To minimize the error rate of spectral estimation, efforts should be made to attenuate noise and retain significant spectral peaks before identifying candidate spectral peaks. The main idea is to exploit the temporal correlation of atmospheric echoes while suppressing random noise which is highly uncorrelated. Suppose successive pulses observe the same moving air parcel. The received signal changes slowly.
Similarly, its phase also changes smoothly. Therefore,
successive slow-time samples are strongly correlated.

Because of this difference, the researchers used mutual convolution to measure the similarity between delayed versions of the slow-time signal.

The method is described below:

First, take a row vector $P = lr((p_1, p_2 , dots , p_N))$ of one range bin from the preprocessing data $X$. Then, take out vectors with equal length from $P$ to form a new row vector. Here the researchers used half the size of the orignal vector as new vector. Let these constructed vectors be:

$ V_(r 1) = lr((p_1, p_2 , dots , p_(N\/2))) $

The half length for sequences allows several overlapping signal segments to be created. The paper defines number of delay points I as:
$ I = N / (2(n-1)) $

where

- N = total length of vector $P$
- n = desired number of extracted vectors
From this a new matrix can be given as:

$ V = lr([V_(r 1), V_(r 1), , dots, V_(r n)]) $

Now mutual convolution is performed:

$
      V_(C 1) & = V_(r 2) * V_(r 1)^"HR" \
      V_(C 2) & = V_(r 3) * V_(r 1)^"HR" \
              & dots.v \
  V_(C (n-1)) & = V_(r n) * V_(r 1)^"HR"
$
Where HR means that the conjugate and then reverse order. 
After the above calculation, the number of convolution results is $n-1$ and the length of each calculation result becomes $N -1$. To maintain the same time complexity and velocity resolution of calculation, a new matrix can be generated by extracting data from the middle of the vector, with the number being $N\/2$, given as:

#set math.mat(row-gap: .6em)
$
  lr([V'_C]) =
  mat(
    delim: "[",
    V'_(C 1);
    V'_(C 2);
    dots.v;
    V'_(C (n-1))
  ) =
  mat(
    delim: "[",
    display(V_(C 1)lr((N/4:(3N)/4)));
    display(V_(C 2)lr((N/4:(3N)/4)));
    display(dots.v);
    display(V_(C (n-1))lr((N/4:(3N)/4)))
  )
$

Then maximum of power spectra of each row is computed:

$ V'_(c f) = lr(
	[
		max{
			lr(|cal(F)lr(([V'_c]), size: #(1.5em))|, size: #(1.5em))
		}
	]
) $

where $cal(F)$ represents Fourier transform. The maximum of $V'_(c f)$ corresponds to some optimial solution $X_r$ (let that be $V'_(C k)$). In practice the researchers choose to keep adjacent readings ($V'_(C (k-1))$ and $V'_(C (k+1))$) which are kept as candidate peaks or suboptimal soluions $X'_r$.

== MCLMS
MCLMS is a adaptive filter. Its purpose is to further suppress residual clutter and random noise after the Mutual Convolution stage has identified the most coherent signal segment. The algorithm uses the optimal convolution result $X_r$ and the adjacent suboptimal convolution result $X'_r$ as the input and desired signals of a CLMS adaptive filter. The underlying assumption is that these two signals contain the same atmospheric echo because they originate from adjacent delay windows, while their noise and clutter components are largely uncorrelated. By adapting the filter to transform $X_r$ into $X'_r$, the filter reinforces the common atmospheric component and suppresses the components that differ between the two signals. Unlike a conventional adaptive filter, where adaptation and filtering occur simultaneously, the proposed MCLMS algorithm separates these operations into two stages. During the first stage, the filter is used only for training -- the adaptive filter coefficients are continuously updated until they converge. After convergence, the learned coefficients are copied and reused in a second filtering pass to generate the final filtered output.
The specific calculation process is as follows.
The optimal solution is represented as an $\N/2 - N\/2$ - dimensional row vector and the length of the coefficient filter is denoted as $k$. First a normalization factor is calculated.
$ u = 1/(sum_(j=1)^(N\/2)|X_r (j)|^2 ) $

This balances how coefficients are adjusted even when one input is much larger in comparison to others. The adaptive filter has a length of $k$ coefficients. For every sample position $j$, an input vector $X$ is constructed from the samples of $X_r$. If there are insufficient previous samples at the beginning of the sequence, zeros are inserted.

#let tthick = $thick thick$;

$ X = cases(gap: #(.5em),
	display("zeros"lr((1,tthick k-j, tthick X_r (1:j))) quad & "," j < k),
	display(X_r (j-k+1:j) quad quad & "," j < k)
) quad quad j in {1, tthick 2, tthick dots, N\/2} $

This effectively forms a sliding window over the signal, allowing the adaptive filter to operate as a finite impulse response (FIR) filter. The filter coefficients are initially set to zero,

$ W_1 = 0 $

For each input vector, the filter output is calculated using

$ Y_j = W_1 X^T $

which is simply the dot product between the current coefficient vector and the input vector. The difference between the desired signal $X'_r$ and the filter output produces the estimation error,

$ e_j = X'_(r j) - Y_j $

The coefficients are then updated using

$ W'_1 = 0.98W_1 + u e_j X^H $

The factor 0.98 is a leakage factor that slightly reduces the magnitude of the coefficients during each iteration, preventing them from growing excessively and improving numerical stability

The coefficient update process is repeated for every sample in the signal until all data have been processed. At this stage, the coefficients have converged to values that best represent the common characteristics shared by $X_r$ and $X'_r$. Here we let 
$ W_2 = W'_1 $ In the second pass, the algorithm repeats the filtering operation using the fixed coefficient vector $W_2$ but without further adaptation. Since the coefficients have already converged, the filter produces a stable output $Y_r$, which contains a stronger atmospheric echo and significantly reduced noise and clutter. This filtered signal is subsequently used by the MCCF stage for reliable Doppler peak identification and wind profile estimation.

== Generating the Cost Function
After the Mutual Convolution and MCLMS stages, the radar signal has been significantly cleaned, and a Doppler spectrum has been obtained for every range bin. However multiple spectral peaks may still exist within a single Doppler spectrum. In conventional spectral estimation methods, it is generally assumed that the first range bin contains only one dominant spectral peak, which is selected as the atmospheric echo. The researchers point out that this assumption is not valid for the VORTRAD and other wind profilers because strong ground clutter, interference, and other unwanted echoes often produce multiple prominent peaks in the first range bin. Consequently, selecting the strongest peak directly can result in incorrect wind estimation. To overcome this problem, the paper introduces the Mutual Convolution Cost Function (MCCF), which evaluates candidate spectral peaks using both their spectral power and their physical consistency with neighbouring range bins.

 first step is to calculate the average value corresponding
to the power spectrum of the first range bin, it can be
given as:

$ M_1 = 1/(n-1) sum_(i=1)^(n-1) cal(F)lr((V'_(C i))) $

The resulting average spectrum provides a more stable estimate of the true Doppler spectrum in the first range bin. The algorithm then identifies the strongest peak in this averaged spectrum,

$ M_(1,1) = max|M_1| $
which serves as the initial reference for subsequent peak tracking through higher range bins. For every range bin, the Doppler spectrum is then computed from the MCLMS filtered signal, 
$M_r = |cal(F) (Y_r)| $

To reduce the possibility of selecting insignificant noise peaks, the algorithm first sorts all spectral peaks according to their power and retains at most three candidate peaks within each ST--W. Furthermore, a candidate peak is considered only if its power satisfies

$ M_(r,j) >= 0.4 M_(r"max") $

Where $M_(r"max")$ is maximum spectral peak within the ST--W and $M_(r,j)$ represents the power value corresponding to the
$j$th spectral peak of the $r$th range bin. This threshold removes weak noise peaks.
The algorithm then evaluates how well each candidate peak agrees with the wind velocity estimated in the previous range bin. Atmospheric winds normally vary smoothly with altitude, and therefore the Doppler velocity should also change gradually between adjacent range bins. To quantify this behaviour, the paper defines a velocity cost

$ V_(r+1, j) = 1 - lr(|((M_(r+1) - M_r)d_v)/(alpha V_d)|) $

where
- $d_v$ = velocity resolution
- $V_d$ = maximum wind shear
- $alpha$ = window coefficient, 
- $V_(r+1, j)$ = velocity cost value corresponding to the $j$th
spectral peak of the $(r + 1)$th range bin.

Finally, the algorithm combines two independent criteria to evaluate each candidate peak -- velocity continuity (represented by velocity cost $V_(r+1, j)$) and spectral power of the candidate peak ($M_(r+1, j)$). These two constraints are combined through the MCCF cost function:

$ F_(r+1, j) = w_1 V_(r+1, j) + w_2 M_(r+1, j) quad quad "and" w_1 + w_2 = 1 $ 

where $w_1$ and $w_2$ are weighting factors controlling the relative importance of velocity continuity and spectral power. This weighted cost function ($F_(r+1, j)$) forces selection of candidate peak that simultaneously possess sufficient spectral power and reasonable continuation of the wind profile. The peak with the highest cost value is selected as the atmospheric Doppler peak for that range bin, and the process is repeated for all subsequent range bins until the complete wind profile has been estimated.