= Techniques
== Introduction
First 3 techniques described in this chapter are scalable -- that is transform size is parameterized; the desired length DFT computer can be easily generated by tweaking one or two variables. Moreover R2MDC and R2SDC are more practical compared to in place computer. These 3 methods are radix-2 only.

The last algorithm, Winograd is unscalable and has different implementation for different transform sizes. Winograd is often used in conjunction with Cooley-Tukey decomposition, where performance of smaller DFT has significant contribution in overall performance @HTC-FFT-GT. For Winograd, a scheme for 5 point DFT is derived, at the end evaluation of 16 point Winograd is given.

== Method used in analysis
The initial development, simulation and debugging was done using `Verilator` due to its ease of use. Later, synthesis and implementation were carried out in Vivado. To automate the process of generating implementation reports for multiple point size FFTs in the case of scalable techniques, a TCL script was created and Vivado was run from terminal using the script. The reports such as hardware utilisation, nets, routing summary, timing and power characteristics were obtained using these commands respectively:

#show raw: set text(size: 8pt);
// llength [get_nets -hierarchical]

```tcl
report_utilization -hierarchical
report_route_status -show_all
report_timing_summary
report_power
```

For estimation of timing, a 10ns clock was assumed. // ```tcl create_clock -period 10.000 -name clk [get_ports clk]```
And for power utilisation the toggle rate and static probability was prescribed, (hence doing a vectorless analysis). Input control signals were given toggle rate of 2% and while for inputs 50%. static probability is 95% for input control signals and 50% for data inputs
```tcl
set_switching_activity -toggle_rate 2.0 -static_probability 0.95 [get_ports in_valid]
set_switching_activity -toggle_rate 50.0 -static_probability 0.5 [get_ports {din[*]}]
set_switching_activity -toggle_rate 0.0 -static_probability 0.0 [get_ports rst]
```
With these constraints, tool reports `medium` confidence in power estimation.
A measure of "latency"  is discussed throughout this report which is implied as the time or number of clock cycles required to obtain first output after the first input has been passed.
Throughput is the number of samples the algorithm can process in a cycle. Since here I have included both pipelined and non-pipelined implementations, throughout is defined as:
$
  "Number of samples"/("Number of cycles to process whole input") times "max frequency of operation"
$


#include "dit-radix2-inplace.typ"
#include "dif-R2MDC.typ"
#include "dif-R2SDC.typ"
#include "winograd.typ"
// #include "RFFT.typ"