== RFFT
The Real Fast Fourier Transform (RFFT) is a specialized form of the Fast Fourier Transform (FFT) used for processing real-valued input signals. Since the input sequence contains only real numbers, the RFFT reduces computational complexity compared to a conventional complex FFT by utilizing the symmetry properties of the Discrete Fourier Transform (DFT). RFFT is widely used in digital signal processing applications such as speech processing, biomedical signal analysis, radar systems, and wireless communication.

In this work, a simplified RFFT hardware model was designed and verified using Verilog HDL in Xilinx Vivado 2025.2. The design consists of four modules: Pack Real, FFT Core, Twiddle ROM, and Post Processing. The objective of the implementation is to demonstrate the data flow of an RFFT architecture and verify its operation through behavioral simulation.

The implemented RFFT architecture consists of four major modules:

Pack Real Module

FFT Core

Twiddle Factor ROM

Post Processing Module

These modules are integrated through a top-level module named rfft_top, which controls the overall flow of data between the different processing stages.

The Pack Real module receives eight 8-bit real-valued input samples and combines them into a single 64-bit data bus. This packed representation simplifies the transfer of input data to the FFT processing stage and reduces interface complexity within the hardware design.

The packed input data is then supplied to the FFT Core. In the implemented architecture, the FFT Core performs the fundamental processing operation on the packed real-valued samples and generates separate real and imaginary output components. The processing logic was developed to demonstrate the functional behavior of an RFFT hardware module rather than implementing a fully optimized FFT computation.

A Twiddle Factor Read Only Memory (ROM) module was also implemented to store precomputed coefficient values commonly used in FFT-based processing. The ROM contains fixed-point representations of the cosine and sine coefficients corresponding to different address locations. Although the simplified FFT Core does not fully utilize these coefficients during computation, the inclusion of the Twiddle Factor ROM demonstrates an important architectural component of practical FFT hardware implementations.

The processed output generated by the FFT Core is transferred to the Post Processing Module. This module registers the output values, forwards the real and imaginary components to the external interface, and generates a done signal indicating successful completion of the processing operation.

The complete hardware architecture was verified using Behavioral Simulation in Xilinx Vivado 2025.2. During simulation, eight real-valued input samples ranging from 1 to 8 were applied to the design. The Pack Real module successfully combined these values into a 64-bit packed word represented as 0x0807060504030201. The FFT Core processed the packed input and generated the real output value 0x00000024, corresponding to the decimal value 36, while the imaginary output remained 0x00000000. The assertion of the done signal confirmed the successful completion of the processing sequence.

The simulation results demonstrate that the proposed modular RFFT architecture correctly transfers data through each functional stage and verifies the functionality of the individual hardware modules. Although the implemented FFT Core is a simplified model intended for functional verification, the overall architecture closely follows the modular organization commonly adopted in FPGA-based FFT processing systems. The design provides a clear understanding of data flow, module interaction, and hardware implementation techniques for Real Fast Fourier Transform architectures.



#image("image (2).png")
